auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: ALIYUN_USERNAME
    password: ALIYUN_PASSWORD


images:
  k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.5.0: registry.cn-hangzhou.aliyuncs.com/mcalico/kube-state-metrics:v2.5.0
  k8s.gcr.io/prometheus-adapter/prometheus-adapter:v0.9.1: registry.cn-hangzhou.aliyuncs.com/mcalico/prometheus-adapter:v0.9.1
  registry.k8s.io/ingress-nginx/controller:v1.3.0: registry.cn-hangzhou.aliyuncs.com/mcalico/controller:v1.3.0
  registry.k8s.io/defaultbackend-amd64:1.5: registry.cn-hangzhou.aliyuncs.com/mcalico/defaultbackend-amd64:1.5
  registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.1.1: registry.cn-hangzhou.aliyuncs.com/mcalico/kube-webhook-certgen:v1.1.1
