auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: ALIYUN_USERNAME
    password: ALIYUN_PASSWORD


images:
  # calico
  docker.io/calico/cni:v3.22.2: registry.cn-hangzhou.aliyuncs.com/mcalico/cni
  docker.io/calico/kube-controllers:v3.22.2: registry.cn-hangzhou.aliyuncs.com/mcalico/kube-controllers
  docker.io/calico/node:v3.22.2: registry.cn-hangzhou.aliyuncs.com/mcalico/node
  docker.io/calico/pod2daemon-flexvol:v3.22.2: registry.cn-hangzhou.aliyuncs.com/mcalico/pod2daemon-flexvol
