auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # jenkins
  docker.io/jenkins/jenkins:2.375.2-lts: registry.cn-hangzhou.aliyuncs.com/mcalico/jenkins:2.375.2-lts
