auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: ALIYUN_USERNAME
    password: ALIYUN_PASSWORD


images:
  # calico
  docker.io/calico/cni: registry.cn-hangzhou.aliyuncs.com/mcalico/cni
  docker.io/calico/kube-controllers: registry.cn-hangzhou.aliyuncs.com/mcalico/kube-controllers
  docker.io/calico/node: registry.cn-hangzhou.aliyuncs.com/mcalico/node
  docker.io/calico/pod2daemon-flexvol: registry.cn-hangzhou.aliyuncs.com/mcalico/pod2daemon-flexvol
  k8s.gcr.io/metrics-server/metrics-server: registry.cn-hangzhou.aliyuncs.com/mcalico/metrics-server
  k8s.gcr.io/ingress-nginx/controller: registry.cn-hangzhou.aliyuncs.com/mcalico/ingress-nginx-controller
  k8s.gcr.io/ingress-nginx/kube-webhook-certgen: registry.cn-hangzhou.aliyuncs.com/mcalico/kube-webhook-certgen
  k8s.gcr.io/defaultbackend-amd64: registry.cn-hangzhou.aliyuncs.com/mcalico/defaultbackend-amd64