auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: ALIYUN_USERNAME
    password: ALIYUN_PASSWORD


images:
  k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.5.0: registry.cn-hangzhou.aliyuncs.com/mcalico/kube-state-metrics:v2.5.0

