auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # jenkins

  registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407: docker.io/jiamiao442/kube-webhook-certgen:v20230407
  registry.k8s.io/ingress-nginx/controller:v1.8.2: docker.io/jiamiao442/controller:v1.8.2

