auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # jenkins
  docker.io/jenkins/jenkins:2.375.2-lts-jdk11: registry.cn-hangzhou.aliyuncs.com/mcalico/jenkins:2.375.2-lts-jdk11
  registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b: registry.cn-hangzhou.aliyuncs.com/mcalico/kube-webhook-certgen:v20230407@sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b

