auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # jenkins

  registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407: registry.cn-hangzhou.aliyuncs.com/mcalico/kube-webhook-certgen:v20230407
  registry.k8s.io/ingress-nginx/controller:v1.8.2: registry.cn-hangzhou.aliyuncs.com/mcalico/controller:v1.8.2