# This is a basic workflow to help you get started with Actions

name: image-sync
on:
  push:
    branches: [ image-syncer-hub-to-aliyun ]
  pull_request:
    branches: [ image-syncer-hub-to-aliyun ]
  schedule:
    - cron: '0 23 * * 1'

env:
  IMAGE_SYNCER_VERSION: v1.3.1
  ALIYUN_USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  ALIYUN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
  
jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install image-sync tool
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/${IMAGE_SYNCER_VERSION}/image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        tar -zxf image-syncer-${IMAGE_SYNCER_VERSION}-linux-amd64.tar.gz
        
    - name: init config.yaml with env
      run: |
        sed -i "s#ALIYUN_USERNAME#${ALIYUN_USERNAME}#g" config.yaml
        sed -i "s#ALIYUN_PASSWORD#${ALIYUN_PASSWORD}#g" config.yaml
      
    - name: sync images
      run: |
        ./image-syncer --proc=5 --config=config.yaml  --retries=2
